/*
* generated by Xtext
*/
package famix;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class M3xUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return famix.ui.internal.M3xActivator.getInstance().getInjector("famix.M3x");
	}
	
}
